### PR TITLE
complete new lesson on the use of backticks.

### PR DESCRIPTION
**Pull request by plijnzaad**
This lesson on the use of backticks (aka command substitution) was written as an addition to shell-novice, but it was deemed too much and shell-extras seems a better fit. The lesson in its current shape refers to topics in shell-novice (specifically to Loops, Pipes and Filters, and Shell Scripts), this may need some editorial work. Likewise, I carefully avoided the use of variables (mostly), but that is unnatural in the context of shell-extras which does have a lesson on them. Oh well, I hope it's useful.

### CODE REVIEW

**Comment by twitwi** [comment]
Just saw the PR title in my github notification list :)

Did you consider using $() instead of backticks?

I'm not too sure which one should be used (I know that I use $() as it can be nested, even though I would not recommend using this feature too much).
It seems the $() might be preferred [1], but again, I'm not so sure.

[1] http://stackoverflow.com/questions/9405478/command-substitution-backticks-or-dollar-sign-paren-enclosed#9406350

**Comment by wking** [comment]
On Thu, Mar 10, 2016 at 12:53:18PM -0800, Rémi Emonet wrote:

> It seems the $() might be preferred [1]…

bash(1)'s “Command Substitution” section has:

  When the old-style backquote form of substitution is used…

which suggests (to me) that `…` is kept for backwards compatibility,
and that $(…) is preferred.

**Comment by wking** [comment]
On Thu, Mar 10, 2016 at 12:53:18PM -0800, Rémi Emonet wrote:

> Did you consider using $() instead of backticks?

And it looks like the answer to that is “yes” [1](https://github.com/plijnzaad/shell-extras/commit/7c9026aabf8d316d3e184763df8d0ac39639f051#diff-801d0911b5b952524656ab197afd0dfeR201).

**Comment by plijnzaad** [comment]
I'd be happy to replace all the backticks with $(). I  chose the former because they are, for better or worse, more well known and more often used (I do mention and promote the $() syntax, a bit, in the lesson)

**Comment by kynan** [comment]
@plijnzaad Please, please switch any use of backticks to $(). We really shouldn't be teaching folks deprecated syntax / habits.

**Comment by plijnzaad** [comment]
I kind of forgot a bit about this PR; has it been merged into shell-extras or elsewhere? I was about to delete my fork ... Is there anything that needs to be done?

**Comment by gdevenyi** [comment]
This looks good to me, +1 for merge.

**Pull request merged**
