### PR TITLE
Update to new SWC template

### PR DESCRIPTION
**Pull request by brandoncurtis**
In case there is some additional change in #37 that is encumbering its merge, this PR is my attempt at a minimal transfer of the existing contents of this repo in a975469c9053fa1ebf3e6a017199c04b7986597d into the SWC template at swcarpentry/styles@9f34e6e952d0d3ab25df0eef4e65a521d2ba4c88.

I only modified the content where it was necessary to make it compatible with the new formatting guidelines.  I have just finished SWC instructor training and I would love to help improve this lesson, but the style should be updated first to match the newest template.

**repo maintainers:** if this is redundant to #37, my apologies.  Please let me know how I can improve this PR and how @vuw-ecs-kevin and I can contribute effectively to this lesson :white_check_mark:

### CODE REVIEW

**Comment by vuw-ecs-kevin** [comment]
> Please let me know how I can improve this PR and how @vuw-ecs-kevin
> and I can contribute effectively to this lesson

Just to say that I have nothing more to offer in terms of getting the

`swcarpentry/shell-extras`

material refactored so as to use the current SWC/DC/LC styles template.

All the work for doing that was done in my PR 37, and even that merely mimiced
what Greg had done elsewhere and so was already known to be an approach 
that had been applied to other "old-style" lesson content, with the case for doing
it to `swcarpentry/shell-extras`  stated, and even  "approved", back in January, 
however this email, also from January,

http://lists.software-carpentry.org/pipermail/discuss/2017-January/004982.html

which is referred to at the start of PR 37, but which you may not have clicked 
through to, does offer a reason why nothing, of an "official SWC" nature, has 
happened within `swcarpentry/shell-extras`itself.

Also worth noting, is that parts of the `swcarpentry/shell-extras` material are being 
canibalised, in a piecemeal fashion, as  noted in my comments about the HPC 
scaffolding effort, so perhaps there is no longer a view, held by those directing 
SWC/DC/LC, that such a lesson, one pulling the current set of episodes and other
related content, together, is needed, within the "official" curriculum, such as one 
exists, in which case `swcarpentry/shell-extras` would seem likely to continue to 
lie fallow.

As to whether a second PR requesting the same thing as another PR is 
enough to change/generate an opinion is unclear. however, until an official 
opinion is actually expressed, one way or another, there is clearly still potential
for people, like yourself, to try and do work on `swcarpentry/shell-extras`, that 
they might be better advised to use their time for elsewhere, within SWC/DC/LC.

**Comment by brandoncurtis** [comment]
#37 was merged, so this is redundant!

**Comment by vuw-ecs-kevin** [comment]
Posting/Duplicating  this here so that Brandon gets to see it.

I'll probably end up cross-posting between this PR and Brandon's here.
or more likely duplicating this comment, but I wanted to point out that
what got pulled in by this PR, actually goes a couple of stages further
than the mere "Swap to jekyll 2", in that it also contains (should really
have been on a seperate branch) some early thoughts I had had about
simple changes to the underlying styles template that would allow for
a correct navigation of the Lesson content, when viewing offline.

These changes don't affect the L&F of this lesson (one of the nice
things about the extra approach), however, anyone cloning it may
not be getting exactly what they think they are getting.

If there's a need to back those extras out, then I can look to do that.

FWIW, I decided to develop the "fully offline capable" idea in a standalone
lesson that I have since created here:

https://github.com/vuw-ecs-kevin/offline-capable-lesson

with the rendered version visble here:

https://vuw-ecs-kevin.github.io/offline-capable-lesson/

**Comment by rgaiacs** [comment]
@vuw-ecs-kevin Could you submit a pull request to https://github.com/swcarpentry/styles with the "fully offline capable"? Sorry if you already submited and I lost track of it.

**Pull request closed without merging**
