### PR TITLE
Update 07-aliases.md

### PR DESCRIPTION
**Pull request by MikeMineter**
1. fixed output format.... I hope.
2. added a warning to concatenate with >> not just one > to overwrite.

### CODE REVIEW

**Comment by MikeMineter** [comment]
Seeking to tidy a couple of details on formatting and to reduce risk that .bashrc be overwritten.
This is a pull request that also meets my checkout as a trainer - I hope.

**Comment by gdevenyi** [comment]
Thanks! Can you please update your formatting of the redirects to be backticked so they get formatted as code?

**Comment by MikeMineter** [comment]
I hope I have accomplished that – got into a knot with commits and the pull, accidentally closing then reopening.

Mike

**Comment by gdevenyi** [comment]
Thanks for the contribution!

**Pull request merged**
