### PR TITLE
Use remote theme

### PR DESCRIPTION
**Pull request by fmichonneau**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Hi @fmichonneau is this an automated conversion or manual?

**Comment by ErinBecker** [comment]
@gdevenyi - this is a manual update.

**Comment by ErinBecker** [comment]
Fixes https://github.com/carpentries-incubator/shell-extras/issues/62

**Comment by gdevenyi** [comment]
Due to the move of this lesson I have no commit access anymore so I can't approve/merge this, but it looks fine.

**Comment by gcapes** [comment]
I also no longer have maintainer access on this. Not sure whether that was the plan?

**Pull request merged**
